package com.rapid7.armor.xact;

public class DistXactRecord {
  public final static String CURRENT_MARKER = "CURRENT";
  private String current;
  private String previous;
  private Long currentTime;
  private Long previousTime;
  // Denotes this baseline was autogenerated to identify as new table.
  private boolean autoCurrent;

  public DistXactRecord(ArmorXact armorTransaction, DistXactRecord previous) {
    this.current = armorTransaction.getTarget();
    this.currentTime = armorTransaction.getTime();
    if (previous != null) {
      this.previous = previous.current;
      this.previousTime = previous.getPreviousTime();
    }
  }

  public DistXactRecord(Object current, Object currentTime, Object previous, Object previousTime) {
    this.current = current.toString();
    if (currentTime != null) {
        if (currentTime instanceof String)
            this.currentTime = Long.parseLong(currentTime.toString());
        else if (currentTime instanceof Number)
            this.currentTime = ((Number)currentTime).longValue();
          else
            throw new IllegalArgumentException("Only strings or numbers are accepted for current time");
    }
    if (previous != null)
        this.previous = previous.toString();
    if (previousTime != null) {
        if (previousTime instanceof String)
          this.previousTime = Long.parseLong(previousTime.toString());
        else if (previousTime instanceof Number)
          this.previousTime = ((Number)previousTime).longValue();
        else
          throw new IllegalArgumentException("Only strings or numbers are accepted for previous time");
    }
  }
  
  public boolean getAutoCurrent() {
    return autoCurrent;
  }

  public void setAutoCurrent(boolean autoCurrent) {
    this.autoCurrent = autoCurrent;
  }

  public String getCurrent() {
    return current;
  }
  
  public String getPrevious() {
    return previous;
  }
  
  public Long getCurrentTime() {
    return currentTime;
  }
  
  public Long getPreviousTime() {
    return previousTime;
  }
  
  public static ArmorXact generateNewTransaction(String transaction, DistXactRecord baseline) {
    return new ArmorXact(transaction, baseline.getCurrent(), System.currentTimeMillis(), baseline.getAutoCurrent());
  }
}
